services:
  frontend:
    container_name: mileage
      #image: php:8.1-apache
    build: 
      context: .
      dockerfile: mileage.Dockerfile
    expose:
      - 80
    ports:
      - "8080:80"
    volumes:
      - type: bind #allows code changes without restarting the server everytime
        source: ./src
        target: /var/www/html
    networks:
      - app

  db:
    container_name: db
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: ${DB_PASS} #pass is in .env file
    expose:
      - 3306
    ports:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
        - app

  phpmyadmin:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "8081:80"
    networks:
      - backend
      - app

volumes:
  db:

networks:
  app:
  frontend:
  backend:

