services:
  frontend:
    container_name: mileage
      #image: php:8.1-apache
    build: 
      context: .
      dockerfile: mileage.Dockerfile
    expose:
      - 80
    ports:
      - "8080:80"
    environment:
      PATH: "$PATH:/var/www/html/vendor/bin"
      MYSQL_ROOT_PASSWORD: ${DB_PASS} #pass is in .env file
      MYSQL_DATABASE: 'db'
    volumes:
      - type: bind #allows code changes without restarting the server everytime
        source: ./src
        target: /var/www/html
    networks:
      app:
        ipv4_address: 10.5.0.2

  db:
    container_name: db
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: ${DB_PASS} #pass is in .env file
    expose:
      - 3306
    ports:
      - 3306
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    networks:
      app:
        ipv4_address: 10.5.0.3

  phpmyadmin:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASS}
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASS} #pass is in .env file
    ports:
      - "8081:80"
    networks:
      app:
        ipv4_address: 10.5.0.4

volumes:
  db:

networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

