services:
  frontend:
    image: php:8.1-apache
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - type: bind #allows code changes without restarting the server everytime
        source: ./src
        target: /var/www/html
    networks:
      - app
  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
        - app

volumes:
  db:

networks:
  app:
  frontend:
  backend:

